// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currency.sql

package sqlc

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, code FROM currencies
`

type ListCurrenciesRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

func (q *Queries) ListCurrencies(ctx context.Context) ([]ListCurrenciesRow, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrenciesRow
	for rows.Next() {
		var i ListCurrenciesRow
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (currency_id, rate, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (currency_id)
DO UPDATE SET rate = EXCLUDED.rate, updated_at = NOW()
`

type UpsertExchangeRateParams struct {
	CurrencyID int64           `json:"currency_id"`
	Rate       decimal.Decimal `json:"rate"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate, arg.CurrencyID, arg.Rate)
	return err
}
