// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const getCurrencyIdByCode = `-- name: GetCurrencyIdByCode :one
SELECT id FROM currencies WHERE code = $1
`

func (q *Queries) GetCurrencyIdByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, getCurrencyIdByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRate = `-- name: GetRate :one
SELECT er.rate, c.unit
FROM exchange_rates er
JOIN currencies c ON c.id = er.currency_id
WHERE c.code = $1
`

type GetRateRow struct {
	Rate decimal.Decimal `json:"rate"`
	Unit decimal.Decimal `json:"unit"`
}

func (q *Queries) GetRate(ctx context.Context, code string) (GetRateRow, error) {
	row := q.db.QueryRow(ctx, getRate, code)
	var i GetRateRow
	err := row.Scan(&i.Rate, &i.Unit)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, code FROM currencies
`

type ListCurrenciesRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

func (q *Queries) ListCurrencies(ctx context.Context) ([]ListCurrenciesRow, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrenciesRow
	for rows.Next() {
		var i ListCurrenciesRow
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrenciesWithRate = `-- name: ListCurrenciesWithRate :many
SELECT
    c.id,
    c.code,
    c.name,
    c.unit,
    er.rate,
    er.updated_at
FROM currencies c
LEFT JOIN exchange_rates er ON er.currency_id = c.id
`

type ListCurrenciesWithRateRow struct {
	ID        int64               `json:"id"`
	Code      string              `json:"code"`
	Name      string              `json:"name"`
	Unit      decimal.Decimal     `json:"unit"`
	Rate      decimal.NullDecimal `json:"rate"`
	UpdatedAt pgtype.Timestamptz  `json:"updated_at"`
}

func (q *Queries) ListCurrenciesWithRate(ctx context.Context) ([]ListCurrenciesWithRateRow, error) {
	rows, err := q.db.Query(ctx, listCurrenciesWithRate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrenciesWithRateRow
	for rows.Next() {
		var i ListCurrenciesWithRateRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Rate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (currency_id, rate, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (currency_id)
DO UPDATE SET rate = EXCLUDED.rate, updated_at = NOW()
`

type UpsertExchangeRateParams struct {
	CurrencyID int64           `json:"currency_id"`
	Rate       decimal.Decimal `json:"rate"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate, arg.CurrencyID, arg.Rate)
	return err
}
