// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	ID         int64          `json:"id"`
	WalletID   int64          `json:"wallet_id"`
	CurrencyID int64          `json:"currency_id"`
	Amount     pgtype.Numeric `json:"amount"`
}

type Currency struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
	Unit string `json:"unit"`
}

type ExchangeRate struct {
	ID         int64              `json:"id"`
	CurrencyID int64              `json:"currency_id"`
	Rate       pgtype.Numeric     `json:"rate"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	Nickname      pgtype.Text        `json:"nickname"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
