// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type Balance struct {
	ID         int64           `json:"id"`
	WalletID   int64           `json:"wallet_id"`
	CurrencyID int64           `json:"currency_id"`
	Amount     decimal.Decimal `json:"amount"`
}

type Currency struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
	Unit string `json:"unit"`
}

type ExchangeRate struct {
	ID         int64              `json:"id"`
	CurrencyID int64              `json:"currency_id"`
	Rate       decimal.Decimal    `json:"rate"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	WalletNumber string             `json:"wallet_number"`
	Nickname     string             `json:"nickname"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
