// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

type Querier interface {
	CreateExchangeLog(ctx context.Context, arg CreateExchangeLogParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTransferLog(ctx context.Context, arg CreateTransferLogParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteRefreshToken(ctx context.Context, token string) error
	GetRate(ctx context.Context, code string) (GetRateRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetWallet(ctx context.Context, walletNumber string) (GetWalletRow, error)
	GetWalletBalance(ctx context.Context, arg GetWalletBalanceParams) (GetWalletBalanceRow, error)
	GetWalletBalanceLock(ctx context.Context, arg GetWalletBalanceLockParams) (GetWalletBalanceLockRow, error)
	GetWalletBalances(ctx context.Context, walletNumber string) ([]GetWalletBalancesRow, error)
	GetWallets(ctx context.Context, userID int64) ([]GetWalletsRow, error)
	ListCurrencies(ctx context.Context) ([]ListCurrenciesRow, error)
	ListCurrenciesWithRate(ctx context.Context) ([]ListCurrenciesWithRateRow, error)
	UpsertBalance(ctx context.Context, arg UpsertBalanceParams) (decimal.Decimal, error)
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error
}

var _ Querier = (*Queries)(nil)
