// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlc

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, wallet_number, nickname) VALUES($1, $2, $3) RETURNING id, user_id, wallet_number, nickname, created_at
`

type CreateWalletParams struct {
	UserID       int64  `json:"user_id"`
	WalletNumber string `json:"wallet_number"`
	Nickname     string `json:"nickname"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.WalletNumber, arg.Nickname)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletNumber,
		&i.Nickname,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :many
SELECT 
    w.user_id,
    c.code,
    c.name,
    COALESCE(b.amount, 0) AS amount
FROM wallets w
JOIN currencies c ON true
LEFT JOIN balances b 
    ON b.currency_id = c.id
    AND b.wallet_id = w.id
WHERE w.wallet_number = $1
ORDER BY COALESCE(b.amount, 0) DESC
`

type GetWalletBalanceRow struct {
	UserID int64           `json:"user_id"`
	Code   string          `json:"code"`
	Name   string          `json:"name"`
	Amount decimal.Decimal `json:"amount"`
}

func (q *Queries) GetWalletBalance(ctx context.Context, walletNumber string) ([]GetWalletBalanceRow, error) {
	rows, err := q.db.Query(ctx, getWalletBalance, walletNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWalletBalanceRow
	for rows.Next() {
		var i GetWalletBalanceRow
		if err := rows.Scan(
			&i.UserID,
			&i.Code,
			&i.Name,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalletByWalletNumber = `-- name: GetWalletByWalletNumber :one
SELECT user_id, wallet_number, nickname FROM wallets WHERE wallet_number = $1
`

type GetWalletByWalletNumberRow struct {
	UserID       int64  `json:"user_id"`
	WalletNumber string `json:"wallet_number"`
	Nickname     string `json:"nickname"`
}

func (q *Queries) GetWalletByWalletNumber(ctx context.Context, walletNumber string) (GetWalletByWalletNumberRow, error) {
	row := q.db.QueryRow(ctx, getWalletByWalletNumber, walletNumber)
	var i GetWalletByWalletNumberRow
	err := row.Scan(&i.UserID, &i.WalletNumber, &i.Nickname)
	return i, err
}

const getWallets = `-- name: GetWallets :many
SELECT wallet_number, nickname FROM wallets WHERE user_id = $1
`

type GetWalletsRow struct {
	WalletNumber string `json:"wallet_number"`
	Nickname     string `json:"nickname"`
}

func (q *Queries) GetWallets(ctx context.Context, userID int64) ([]GetWalletsRow, error) {
	rows, err := q.db.Query(ctx, getWallets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWalletsRow
	for rows.Next() {
		var i GetWalletsRow
		if err := rows.Scan(&i.WalletNumber, &i.Nickname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
