// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlc

import (
	"context"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, wallet_number, nickname) VALUES($1, $2, $3) RETURNING id, user_id, wallet_number, nickname, created_at
`

type CreateWalletParams struct {
	UserID       int64  `json:"user_id"`
	WalletNumber string `json:"wallet_number"`
	Nickname     string `json:"nickname"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.WalletNumber, arg.Nickname)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletNumber,
		&i.Nickname,
		&i.CreatedAt,
	)
	return i, err
}
